name       : perl-tie-cycle
version    : '1.227'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Tie-Cycle-1.227.tar.gz : 7838335791e71a3b33b8a19de3052949e1890a4823def6397823c99222fa1dd8
homepage   : https://github.com/briandfoy/tie-cycle
license    : Artistic-2.0
component  : programming.perl
summary    : Tie::Cycle - Cycle through a list of values via a scalar
description: |
    You use Tie::Cycle to go through a list over and over again. Once you get to the end of the list, you go back to the beginning. You don't have to worry about any of this since the magic of tie does that for you.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
