name       : perl-tie-cycle
version    : '1.225'
release    : 3
source     :
    - https://github.com/briandfoy/tie-cycle/archive/release-1.225.tar.gz : 92fd110616793e1b032e9e17c3d38cd1ba39d71c431704e80bdafa24daa0749d
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/briandfoy/tie-cycle
summary    : Tie::Cycle - Cycle through a list of values via a scalar.
description: |
    Tie::Cycle Perl module allows you to create an array that continually cycles through its elements no matter what index you use.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
