name       : perl-tie-cycle
version    : '1.226'
release    : 5
source     :
    - https://github.com/briandfoy/tie-cycle/archive/refs/tags/release-1.226.tar.gz : efd649aae979d45ae440b012427a3164c4d7a7cee8cd9e763f9e2a6fd17a6b98
license    : Artistic-2.0
component  : programming.perl
homepage   : https://github.com/briandfoy/tie-cycle
summary    : Tie::Cycle - Cycle through a list of values via a scalar.
description: |
    Tie::Cycle Perl module allows you to create an array that continually cycles through its elements no matter what index you use.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
